#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'voronikon' script calculates inter-chain interfaces area statistical pseudo-energy
for protein complexes with peptides that can contain non-canonical amino acid residues.

Options:
    --input-receptor              string     input file path for receptor, must be in PDB or mmCIF format
    --input-ligand                string     input file path for ligand, must be in SDF format
    --input-complex               string     input file path for receptor+ligand complex input, must be in PDB or mmCIF format
    --scoring-mode                string     scoring mode in {'voromqa', 'sas_voromqa', 'vorochipmunk', 'vorochipmunk_en', 'all'}, default is 'vorochipmunk'
    --output-id                   string     string to use as the output ID, default is '' to not output any ID
    --output-table-file           string     output table file path, default is '_stdout' to print to stdout
    --output-details-dir          string     output directory path for details, default is '' to not output details
    --print-mode                  string     printing to stdout mode, can be 'h' or 'v', default is 'h'
    --estimate-tolerance                     flag to stimate pocket tolerance to all ligand atom types 
    --help | -h                              flag to display help message and exit

Standard output:
    space-separated table of scores
    
Examples:

    voronikon --input-receptor "./receptor.pdb" --input-ligand "./ligand.sdf"
    
    voronikon --input-receptor "./receptor.pdb" --input-ligand "./ligand.sdf" --print-mode v
    
    voronikon --input-receptor './receptor.pdb" --input-ligand "./ligand.sdf" --output-table-file "./results.txt"

    voronikon --input-receptor "./receptor.pdb" --input-ligand "./ligand.sdf" --scoring-mode "voromqa"
    
    voronikon --input-complex "./complex.pdb" --print-mode v --scoring-mode "voromqa" --output-id "test1"

EOF
exit 1
}

################################################################################

export LANG=C
export LC_ALL=C

SCRIPTDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

readonly ZEROARG=$0
ALLARGS=("$@")

if [ -z "$1" ]
then
	print_help_and_exit
fi

INPUT_RECEPTOR=""
INPUT_LIGAND=""
INPUT_COMPLEX=""
OUTPUT_ID=""
OUTPUT_TABLE_FILE="_stdout"
OUTPUT_DETAILS_DIR=""
SCORING_MODE="vorochipmunk"
PRINT_MODE="h"
TOLERANCE_ATOM_TYPE=""
ESTIMATE_TOLERANCE="false"
SKIP_SUPPLEMENTARY_DESCRIPTORS="false"
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	--input-receptor)
		INPUT_RECEPTOR="$OPTARG"
		shift
		;;
	--input-ligand)
		INPUT_LIGAND="$OPTARG"
		shift
		;;
	--input-complex)
		INPUT_COMPLEX="$OPTARG"
		shift
		;;
	--output-id)
		OUTPUT_ID="$OPTARG"
		shift
		;;
	--output-table-file)
		OUTPUT_TABLE_FILE="$OPTARG"
		shift
		;;
	--output-details-dir)
		OUTPUT_DETAILS_DIR="$OPTARG"
		shift
		;;
	--scoring-mode)
		SCORING_MODE="$OPTARG"
		shift
		;;
	--print-mode)
		PRINT_MODE="$OPTARG"
		shift
		;;
	--tolerance-atom-type)
		TOLERANCE_ATOM_TYPE="$OPTARG"
		shift
		;;
	--skip-supplementary-descriptors)
		SKIP_SUPPLEMENTARY_DESCRIPTORS="$OPTARG"
		shift
		;;
	--estimate-tolerance)
		ESTIMATE_TOLERANCE="true"
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

if [ -n "$INPUT_COMPLEX" ]
then
	if [ -n "$INPUT_RECEPTOR" ] || [ -n "$INPUT_LIGAND" ]
	then
		echo >&2 "Error: conflict with input arguments, both complex and receptor and/or ligand provided"
		exit 1
	fi
	
	if [ ! -s "$INPUT_COMPLEX" ]
	then
		echo >&2 "Error: no input complex file '$INPUT_COMPLEX'"
		exit 1
	fi
else
	if [ -z "$INPUT_RECEPTOR" ]
	then
		echo >&2 "Error: no input receptor file provided"
		exit 1
	fi
	
	if [ -z "$INPUT_LIGAND" ]
	then
		echo >&2 "Error: no input ligand file provided"
		exit 1
	fi
	
	if [ -n "$INPUT_RECEPTOR" ] && [ ! -s "$INPUT_RECEPTOR" ]
	then
		echo >&2 "Error: no input receptor file '$INPUT_RECEPTOR'"
		exit 1
	fi
	
	if [ -n "$INPUT_LIGAND" ] && [ ! -s "$INPUT_LIGAND" ]
	then
		echo >&2 "Error: no input ligand file '$INPUT_LIGAND'"
		exit 1
	fi
fi

if [ "$SCORING_MODE" != "voromqa" ] && [ "$SCORING_MODE" != "sas_voromqa" ] && [ "$SCORING_MODE" != "vorochipmunk" ] && [ "$SCORING_MODE" != "vorochipmunk_en" ] && [ "$SCORING_MODE" != "all" ]
then
	echo >&2 "Error: invalid scoring mode '$SCORING_MODE', must be 'voromqa' or 'sas_voromqa' or 'vorochipmunk' or 'vorochipmunk_en'"
	exit 1
fi

if [ "$PRINT_MODE" != "h" ] && [ "$PRINT_MODE" != "v" ]
then
	echo >&2 "Error: invalid printing mode '$PRINT_MODE', must be 'h' or 'v'"
	exit 1
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

if [ -n "$INPUT_COMPLEX" ]
then
	NAMEPREFIX="$(basename ${INPUT_COMPLEX} .pdb)"
	NAMEPREFIX="$(basename ${NAMEPREFIX} .cif)"
	${SCRIPTDIR}/tools/split-complex-into-receptor-and-ligand "$INPUT_COMPLEX" "${TMPLDIR}/${NAMEPREFIX}_receptor.pdb" "${TMPLDIR}/${NAMEPREFIX}_ligand.sdf"
	
	if [ ! -s "${TMPLDIR}/${NAMEPREFIX}_receptor.pdb" ] || [ ! -s "${TMPLDIR}/${NAMEPREFIX}_ligand.sdf" ]
	then
		echo >&2 "Error: failed to split ${INPUT_COMPLEX} into receptor and ligand files."
		exit 1
	fi
	
	${SCRIPTDIR}/voronikon "${ALLARGS[@]}" --input-complex "" --input-receptor "${TMPLDIR}/${NAMEPREFIX}_receptor.pdb" --input-ligand "${TMPLDIR}/${NAMEPREFIX}_ligand.sdf"
	
	exit 0
fi

if [ "$SCORING_MODE" == "all" ]
then
	for SUBMODE in vorochipmunk vorochipmunk_en voromqa sas_voromqa
	do
		ADDITIONAL_OPTIONS=""
		
		if [ "$SUBMODE" != "sas_voromqa" ]
		then
			ADDITIONAL_OPTIONS=" --skip-supplementary-descriptors true"
		fi
		
		if [ -n "$OUTPUT_DETAILS_DIR" ]
		then
			ADDITIONAL_OPTIONS="${ADDITIONAL_OPTIONS} --output-details-dir ${OUTPUT_DETAILS_DIR}/${SUBMODE}"
		fi
		
		${SCRIPTDIR}/voronikon "${ALLARGS[@]}" --scoring-mode "$SUBMODE" ${ADDITIONAL_OPTIONS} --print-mode v --output-table-file _stdout \
		| grep -E -v '^scoring_mode\s' \
		> "${TMPLDIR}/subresult"
		
		if [ ! -s "${TMPLDIR}/subresult" ]
		then
			echo >&2 "Error: failed to run in scoring mode '${SUBMODE}'."
			exit 1
		fi
		
		if [ "$SUBMODE" == "vorochipmunk" ]
		then
			cat "${TMPLDIR}/subresult" \
			| grep -E '^ID\s|^input_receptor\s|^input_ligand\s|^receptor_atoms\s|^ligand_atoms\s|^iface_clash_score\s'
		fi
		
		cat "${TMPLDIR}/subresult" \
		| grep -E '^iface_area|^iface_energy|^per_unit_area_iface_|^mean_|^sd_|^min_|^max_' \
		| sed "s|^|${SUBMODE}_|"
		
		cat "${TMPLDIR}/subresult" \
		| grep -E '^ligand_sasa\s|ligand_volume\s'
	done \
	> "${TMPLDIR}/all_results_v"
	
	{
		cat "${TMPLDIR}/all_results_v" | awk '{print $1}' | tr '\n' ' ' | sed 's/$/\n/'
		cat "${TMPLDIR}/all_results_v" | awk '{print $2}' | tr '\n' ' ' | sed 's/$/\n/'
	} \
	> "${TMPLDIR}/all_results_h"
	
	if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
	then
		mkdir -p "$(dirname "$OUTPUT_TABLE_FILE")"
		cat "${TMPLDIR}/all_results_h" | column -t > "$OUTPUT_TABLE_FILE"
	else
		if [ "$PRINT_MODE" == "v" ]
		then
			cat "${TMPLDIR}/all_results_v" | column -t
		else
			cat "${TMPLDIR}/all_results_h" | column -t
		fi
	fi

	exit 0
fi

if [ "$ESTIMATE_TOLERANCE" == "true" ]
then
	${SCRIPTDIR}/voronikon --input-receptor "$INPUT_RECEPTOR" --input-ligand "$INPUT_LIGAND" --scoring-mode "$SCORING_MODE" --skip-supplementary-descriptors "$SKIP_SUPPLEMENTARY_DESCRIPTORS" --print-mode "h" --output-id "$OUTPUT_ID" \
	> "${TMPLDIR}/nonmutated_scores.txt"
	
	if [ ! -s "${TMPLDIR}/nonmutated_scores.txt" ]
	then
		echo >&2 "Error: failed to run in non-mutated mode before running in mutated mode."
		exit 1f
	fi
	
	cat "${SCRIPTDIR}/tools/canonical_raw_types.txt" \
	| grep -E '^C|^N|^O' \
	| while read -r MUTATION
	do
		${SCRIPTDIR}/voronikon \
		  --input-receptor "$INPUT_RECEPTOR" \
		  --input-ligand "$INPUT_LIGAND" \
		  --scoring-mode "$SCORING_MODE" \
		  --print-mode "h" \
		  --tolerance-atom-type "$MUTATION" \
		  --skip-supplementary-descriptors "true"
	done \
	| awk '{if(NR==1 || $1!="input_receptor"){print $0}}' \
	> "${TMPLDIR}/mutated_scores.txt"
	
	if [ ! -s "${TMPLDIR}/mutated_scores.txt" ]
	then
		echo >&2 "Error: failed to run in mutated mode."
		exit 1
	fi
	
	cd "$TMPLDIR"
	
R --vanilla << 'EOF' > /dev/null
df0=read.table("nonmutated_scores.txt", header=TRUE, stringsAsFactors=FALSE);
df=read.table("mutated_scores.txt", header=TRUE, stringsAsFactors=FALSE);
df0$mean_mutated_iface_energy=mean((df$iface_energy_worst+df$iface_energy_best)*0.5);
df0$sd_mutated_iface_energy=sd((df$iface_energy_worst+df$iface_energy_best)*0.5);
df0$min_mutated_iface_energy=min((df$iface_energy_worst+df$iface_energy_best)*0.5);
df0$max_mutated_iface_energy=max((df$iface_energy_worst+df$iface_energy_best)*0.5);
write.table(df0, file="merged_scores.txt", row.names=FALSE, col.names=TRUE, quote=FALSE, sep=" ");
EOF

	cd - &> /dev/null
	
	if [ ! -s "${TMPLDIR}/merged_scores.txt" ]
	then
		echo >&2 "Error: failed to summarize results of multiple runs."
		exit 1
	fi
	
	if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
	then
		mkdir -p "$(dirname "$OUTPUT_TABLE_FILE")"
		cat "${TMPLDIR}/merged_scores.txt" | column -t > "$OUTPUT_TABLE_FILE"
	else
		if [ "$PRINT_MODE" == "v" ]
		then
			paste \
			  <(cat "${TMPLDIR}/merged_scores.txt" | head -1 | sed 's/\s\+/\n/g') \
			  <(cat "${TMPLDIR}/merged_scores.txt" | tail -1 | sed 's/\s\+/\n/g') \
			| column -t
		else
			cat "${TMPLDIR}/merged_scores.txt" | column -t
		fi
	fi

	exit 0
fi

cat "$INPUT_RECEPTOR" > "${TMPLDIR}/receptor.pdb"

cat "$INPUT_LIGAND" > "${TMPLDIR}/ligand.sdf"

cd "$TMPLDIR"

${SCRIPTDIR}/tools/Knodle --isdf ./ligand.sdf -o "./ligand.mol2"

if [ ! -s "./ligand.mol2" ]
then
	echo >&2 "Error: failed to process the ligand with Knodle"
	exit 1
fi

cat "./ligand.mol2" \
| grep -E '^@<TRIPOS>ATOM' -A 99999 \
| grep -E '^@<TRIPOS>BOND' -B 99999 \
| grep -E -v '^@' \
| awk '{if($2!="H"){print $0}}' \
> ./ligand_table.txt

cat ./ligand_table.txt \
| awk '{print "LIG " $2 NR " " $6}' \
> ./ligand_atom_types.txt

SCORING_MODE_PREFIX=""

if [ -n "$TOLERANCE_ATOM_TYPE" ]
then
	cat ./ligand_atom_types.txt \
	| awk -v newtype=${TOLERANCE_ATOM_TYPE} '{print $1 " " $2 " " newtype}' \
	> ./changed_ligand_atom_types.txt
	
	mv ./changed_ligand_atom_types.txt ./ligand_atom_types.txt
	
	SCORING_MODE_PREFIX="mutated_to_${TOLERANCE_ATOM_TYPE}_"
fi

cat ./ligand_table.txt \
| awk '{print "c<XX>r<1>a<" NR ">R<LIG>A<" $2 NR "> " $3 " " $4 " " $5 " 1.7 el=" $2 " oc=1"}' \
> ./ligand_atoms.pa

NUM_OF_LIGAND_ATOMS="$(cat ./ligand_atoms.pa | wc -l)"

{
cat << 'EOF'
voronota_setup_defaults("-no-load-voromqa-potentials", "-no-load-more-atom-types", "-no-load-mock-voromqa-potential");
voronota_import("-file", "ligand_atoms.pa");
voronota_export_atoms_to_mmcif("-file", "ligand_atoms.cif");
EOF
} \
| ${SCRIPTDIR}/tools/voronota-js --no-setup-defaults

if [ ! -s "./ligand_atoms.cif" ]
then
	echo >&2 "Error: failed to write the ligand to mmCIF file"
	exit 1
fi

{
cat << 'EOF'
voronota_setup_defaults("-no-load-voromqa-potentials", "-no-load-more-atom-types", "-no-load-mock-voromqa-potential");
voronota_import("-file", "receptor.pdb", "-title", "receptor");
voronota_import("-file", "ligand_atoms.cif", "-title", "ligand");
voronota_merge_objects("-names", ["receptor", "ligand"], "-title", "complex");
voronota_pick_objects("-names", ["complex"]);
voronota_export_atoms_to_mmcif("-file", "complex.cif");
EOF
} \
| ${SCRIPTDIR}/tools/voronota-js --no-setup-defaults

if [ ! -s "./complex.cif" ]
then
	echo >&2 "Error: failed to write the protein-ligand complex to mmCIF file"
	exit 1
fi

{
cat "${SCRIPTDIR}/tools/base_blanket_types.txt"
cat ./ligand_atom_types.txt
} \
| grep -E '.' \
| column -t \
> ./custom_blanket_types_zero.txt

if [ "$SKIP_SUPPLEMENTARY_DESCRIPTORS" == "false" ]
then
	read LIGAND_SASA LIGAND_VOLUME <<< "$(${SCRIPTDIR}/tools/voronota-lt --print-cells-chain-level --pdb-or-mmcif-heteroatoms --input './complex.cif' 2> /dev/null | awk '{if($1=="su" && $2=="XX"){print $5 " " $6}}')"
	
	if [ -z "$LIGAND_SASA" ] || [ -z "$LIGAND_VOLUME" ]
	then
		echo >&2 "Error: failed to calculate ligand volume and SASA"
		exit 1
	fi
fi

if [ "$SCORING_MODE" == "voromqa" ]
then
	${SCRIPTDIR}/tools/voronota-js-fast-iface-voromqa \
	  --input "./complex.cif" \
	  --subselect-contacts "[-a1 [-chain XX] -a2! [-chain XX]]" \
	  --blanket \
	  --blanket-types-file "./custom_blanket_types_zero.txt" \
	  --output-ia-contacts-file "./contacts_ia.txt" \
	  --output-ir-contacts-file "./contacts_ir.txt" \
	> "./global_scores_zero.txt"
fi

if [ "$SCORING_MODE" == "sas_voromqa" ]
then
	${SCRIPTDIR}/tools/score-sas-using-mock-voromqa \
	  "./complex.cif" \
	  "./custom_blanket_types_zero.txt" \
	  "[-a1 [-chain XX] -solvent]" \
	> "./global_scores_zero.txt"
fi

if [ "$SCORING_MODE" == "vorochipmunk" ] || [ "$SCORING_MODE" == "vorochipmunk_en" ]
then
	${SCRIPTDIR}/tools/vorochipmunk-blanket \
	  --akbps-layered-lib-weights "$SCORING_MODE" \
	  --input "./complex.cif" \
	  --subselect-contacts "[-a1 [-chain XX] -a2! [-chain XX]]" \
	  --blanket-types-file "./custom_blanket_types_zero.txt" \
	> "./global_scores_zero.txt"
fi

if [ ! -s "./global_scores_zero.txt" ]
then
	echo >&2 "Error: failed to calculate base scores"
	exit 1
fi

read NUM_OF_ATOMS IFACE_AREA IFACE_ENERGY IFACE_CLASH_SCORE <<< "$(tail -1 ./global_scores_zero.txt | awk '{print $2 " " $3 " " $4 " " $6}')"

{
cat ./ligand_atom_types.txt | awk '{print $3}' | sort | uniq
cat "${SCRIPTDIR}/tools/canonical_raw_types.txt"
cat "${SCRIPTDIR}/tools/canonical_raw_types.txt"
} \
| sort | uniq -c | awk '{if($1<2){print $2}}' \
> ./unmatched_ligand_atom_types.txt

if [ -s "./unmatched_ligand_atom_types.txt" ]
then
	{
	while read -r UNKNOWNTYPE
	do
		cat ./ligand_atom_types.txt | awk -v a=${UNKNOWNTYPE} '{if($3==a){print $2}}'
	done < ./unmatched_ligand_atom_types.txt
	} \
	| tr '\n' ',' | sed 's/,$//' \
	> ./list_of_non_canonical_atom_ids.txt
	
	CANONICALSELECTION="$(cat ./list_of_non_canonical_atom_ids.txt | head -1 | awk '{print "[-a1 [-chain XX] -a2! [-chain XX] -a1! [-aname " $1 "]]"}')"
	
	if [ "$SCORING_MODE" == "voromqa" ]
	then
		${SCRIPTDIR}/tools/voronota-js-fast-iface-voromqa \
		  --input "./complex.cif" \
		  --subselect-contacts "$CANONICALSELECTION" \
		  --blanket \
		  --blanket-types-file "./custom_blanket_types_zero.txt" \
		> "./global_scores_canonical.txt"
	fi
	
	if [ "$SCORING_MODE" == "sas_voromqa" ]
	then
		${SCRIPTDIR}/tools/score-sas-using-mock-voromqa \
		  "./complex.cif" \
		  "./custom_blanket_types_zero.txt" \
		  "$(cat ./list_of_non_canonical_atom_ids.txt | head -1 | awk '{print "[-a1 [-chain XX] -solvent -a1! [-aname " $1 "]]"}')" \
		> "./global_scores_canonical.txt"
	fi
	
	if [ "$SCORING_MODE" == "vorochipmunk" ] || [ "$SCORING_MODE" == "vorochipmunk_en" ]
	then
		${SCRIPTDIR}/tools/vorochipmunk-blanket \
		  --akbps-layered-lib-weights "$SCORING_MODE" \
		  --input "./complex.cif" \
		  --subselect-contacts "$CANONICALSELECTION" \
		  --blanket-types-file "./custom_blanket_types_zero.txt" \
		> "./global_scores_canonical.txt"
	fi
	
	if [ ! -s "./global_scores_canonical.txt" ]
	then
		read CANONICAL_IFACE_AREA CANONICAL_IFACE_ENERGY <<< "0 0"
	else
		read CANONICAL_IFACE_AREA CANONICAL_IFACE_ENERGY <<< "$(tail -1 ./global_scores_canonical.txt | awk '{print $3 " " $4}')"
	fi
	
	while read -r UNKNOWNTYPE
	do
		while read -r CANONICALTYPE
		do
			{
			cat "${SCRIPTDIR}/tools/base_blanket_types.txt"
			cat ./ligand_atom_types.txt | awk -v a=${UNKNOWNTYPE} -v b=${CANONICALTYPE} '{if($3==a){print $1 " " $2 " " b}else{print $0}}'
			} \
			| grep -E '.' \
			| column -t \
			> "./custom_blanket_types_shifted.txt"
			
			if [ "$SCORING_MODE" == "voromqa" ]
			then
				${SCRIPTDIR}/tools/voronota-js-fast-iface-voromqa \
				  --input "./complex.cif" \
				  --subselect-contacts "[-a1 [-chain XX] -a2! [-chain XX]]" \
				  --blanket \
				  --blanket-types-file "./custom_blanket_types_shifted.txt" \
				> "./global_scores_shifted.txt"
			fi
			
			if [ "$SCORING_MODE" == "sas_voromqa" ]
			then
				${SCRIPTDIR}/tools/score-sas-using-mock-voromqa \
				  "./complex.cif" \
				  "./custom_blanket_types_shifted.txt" \
				  "[-a1 [-chain XX] -solvent]" \
				> "./global_scores_shifted.txt"
			fi
			
			if [ "$SCORING_MODE" == "vorochipmunk" ] || [ "$SCORING_MODE" == "vorochipmunk_en" ]
			then
				${SCRIPTDIR}/tools/vorochipmunk-blanket \
				  --akbps-layered-lib-weights "$SCORING_MODE" \
				  --input "./complex.cif" \
				  --subselect-contacts "[-a1 [-chain XX] -a2! [-chain XX]]" \
				  --blanket-types-file "./custom_blanket_types_shifted.txt" \
				> "./global_scores_shifted.txt"
			fi
	
			if [ ! -s "./global_scores_shifted.txt" ]
			then
				echo >&2 "Error: failed to calculate shifted scores"
				exit 1
			fi
			
			IFACE_ENERGY_SHIFTED="$(tail -1 ./global_scores_shifted.txt | awk '{print $4}')"
			
			echo "${UNKNOWNTYPE} ${CANONICALTYPE} ${IFACE_ENERGY_SHIFTED}"
		done \
		< "${SCRIPTDIR}/tools/canonical_raw_types.txt" \
		| sort -n -k3,3 \
		> "./sorted_energies_for_shifted.txt"
		
		read IFACE_ENERGY_SHIFTED_LOW_NAME IFACE_ENERGY_SHIFTED_LOW <<< "$(head -1 ./sorted_energies_for_shifted.txt | awk '{print $2 " " $3}')"
		read IFACE_ENERGY_SHIFTED_HIGH_NAME IFACE_ENERGY_SHIFTED_HIGH <<< "$(tail -1 ./sorted_energies_for_shifted.txt | awk '{print $2 " " $3}')"
		
		rm -f "./global_scores_shifted.txt" "./sorted_energies_for_shifted.txt"
		
		echo "${UNKNOWNTYPE} ${IFACE_ENERGY} ${IFACE_ENERGY_SHIFTED_LOW} ${IFACE_ENERGY_SHIFTED_HIGH} ${IFACE_ENERGY_SHIFTED_LOW_NAME} ${IFACE_ENERGY_SHIFTED_HIGH_NAME}" \
		| awk '{print $1 " " ($3-$2) " " ($4-$2) " " $5 " " $6}'
	done \
	< ./unmatched_ligand_atom_types.txt \
	> "./global_energy_shifts_min_max.txt"

	{
	echo "${IFACE_ENERGY} ${IFACE_ENERGY}"
	cat "./global_energy_shifts_min_max.txt" | awk '{print $2 " " $3}'
	} \
	| awk '{energy_low+=$1; energy_high+=$2} END {print energy_low " " energy_high}' \
	> "./global_energy_min_max.txt"

	read IFACE_ENERGY_LOW IFACE_ENERGY_HIGH <<< "$(cat ./global_energy_min_max.txt)"

	{
	echo "noncanonical_atom energy_shift_worst energy_shift_best replacement_atom_worst replacement_atom_best"
	cat "./global_energy_shifts_min_max.txt" | awk '{print $1 " " $3 " " $2 " " $5 " " $4}'
	} \
	| column -t \
	> "./final_result_shifts.txt"
else
	read CANONICAL_IFACE_AREA CANONICAL_IFACE_ENERGY <<< "${IFACE_AREA} ${IFACE_ENERGY}"
	read IFACE_ENERGY_LOW IFACE_ENERGY_HIGH <<< "${IFACE_ENERGY} ${IFACE_ENERGY}"
fi

NUM_OF_RECEPTOR_ATOMS="$(echo ${NUM_OF_ATOMS} ${NUM_OF_LIGAND_ATOMS} | awk '{print ($1-$2)}')"

IFACE_ENERGY_HIGH_PER_UNIT_AREA="$(echo ${IFACE_ENERGY_HIGH} ${IFACE_AREA} | awk '{print ($1/$2)}')"

GLOBALTABLE_HEADER=""
GLOBALTABLE_VALUE=""

if [ -n "$OUTPUT_ID" ]
then
	GLOBALTABLE_HEADER="ID"
	GLOBALTABLE_VALUE="${OUTPUT_ID}"
fi

GLOBALTABLE_HEADER="${GLOBALTABLE_HEADER} input_receptor input_ligand receptor_atoms ligand_atoms iface_area iface_energy_worst iface_energy_best iface_area_canonical iface_energy_canonical iface_clash_score per_unit_area_iface_energy_worst scoring_mode"
GLOBALTABLE_VALUE="${GLOBALTABLE_VALUE} $(basename ${INPUT_RECEPTOR}) $(basename ${INPUT_LIGAND}) ${NUM_OF_RECEPTOR_ATOMS} ${NUM_OF_LIGAND_ATOMS} ${IFACE_AREA} ${IFACE_ENERGY_HIGH} ${IFACE_ENERGY_LOW} ${CANONICAL_IFACE_AREA} ${CANONICAL_IFACE_ENERGY} ${IFACE_CLASH_SCORE} ${IFACE_ENERGY_HIGH_PER_UNIT_AREA} ${SCORING_MODE_PREFIX}${SCORING_MODE}"

if [ -n "$LIGAND_SASA" ] && [ -n "$LIGAND_VOLUME" ]
then
	GLOBALTABLE_HEADER="${GLOBALTABLE_HEADER} ligand_sasa ligand_volume"
	GLOBALTABLE_VALUE="${GLOBALTABLE_VALUE} ${LIGAND_SASA} ${LIGAND_VOLUME}"
fi

{
echo "${GLOBALTABLE_HEADER}"
echo "${GLOBALTABLE_VALUE}"
} \
| column -t \
> "./final_result.txt"

cd - &> /dev/null

if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
then
	mkdir -p "$(dirname "$OUTPUT_TABLE_FILE")"
	cat "${TMPLDIR}/final_result.txt" > "$OUTPUT_TABLE_FILE"
else
	if [ "$PRINT_MODE" == "v" ]
	then
		paste \
		  <(cat "${TMPLDIR}/final_result.txt" | head -1 | sed 's/\s\+/\n/g') \
		  <(cat "${TMPLDIR}/final_result.txt" | tail -1 | sed 's/\s\+/\n/g') \
		| column -t
	else
		cat "${TMPLDIR}/final_result.txt"
	fi
fi

if [ -n "$OUTPUT_DETAILS_DIR" ]
then
	mkdir -p "$OUTPUT_DETAILS_DIR"
	mv "${TMPLDIR}/complex.cif" "${OUTPUT_DETAILS_DIR}/complex.cif"
	mv "${TMPLDIR}/final_result.txt" "${OUTPUT_DETAILS_DIR}/global_scores.txt"
	[ -s "${TMPLDIR}/final_result_shifts.txt" ] && mv "${TMPLDIR}/final_result_shifts.txt" "${OUTPUT_DETAILS_DIR}/non_canonical_parts_in_global_scores.txt"
	[ -s "${TMPLDIR}/contacts_ia.txt" ] && mv "${TMPLDIR}/contacts_ia.txt" "${OUTPUT_DETAILS_DIR}/contacts_inter_atom.txt"
	[ -s "${TMPLDIR}/contacts_ir.txt" ] && mv "${TMPLDIR}/contacts_ir.txt" "${OUTPUT_DETAILS_DIR}/contacts_inter_residue.txt"
fi




