#!/bin/bash

set -euo pipefail

CONDA_ROOT="${HOME}/miniconda3"
CONDA_ENV_NAME="extratools"
CONDA_R="${CONDA_ROOT}/envs/${CONDA_ENV_NAME}/bin/R"

if [ -t 0 ]
then
	echo >&2 "Error: no R script provided on stdin"
	exit 1
fi

if command -v R >/dev/null 2>&1
then
	exec R "$@"
else
	if [ ! -x "$CONDA_R" ]
	then
		echo >&2 "Error: R not found, and Conda env R not executable at ${CONDA_R}"
		exit 1
	fi
	
	exec "$CONDA_R" "$@"
fi
